FROM python:3.11-slim
WORKDIR /src
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend /src/backend
COPY tests /src/tests
CMD ["pytest", "tests/test_performance.py"]