services:
  web:
    build: ./backend
    command: uvicorn backend.bin.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5432"

  test:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.test
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - default
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]

volumes:
  postgres_data:

networks:
  default: 
    name: senvoapi
